/**
 * POSE LIBRARY — Thư viện tư thế người mẫu + Prompt mẫu tối ưu
 */

export const POSE_CATEGORIES = [
    { id: 'all', label: '🔥 Tất cả' },
    { id: 'front', label: '🎯 Chính diện' },
    { id: 'back', label: '🔙 Sau lưng' },
    { id: 'side', label: '📐 Nghiêng 3/4' },
    { id: 'selfie', label: '🤳 Selfie' },
    { id: 'action', label: '🏃 Hành động' },
    { id: 'sitting', label: '💺 Ngồi' },
    { id: 'editorial', label: '📸 Editorial' },
    { id: 'cycling', label: '🚲 Xe đạp' },
    { id: 'driving', label: '🚗 Ô tô' },
    { id: 'running', label: '🏃‍♀️ Chạy bộ' },
    { id: 'pickleball', label: '🏓 Pickleball' },
    { id: 'bikini', label: '👙 Bikini' },
    { id: 'gym', label: '💪 GYM' },
    { id: 'swimwear', label: '🏊 Đồ bơi' },
    { id: 'luxury', label: '💎 Luxury' },
]

export const POSE_LIBRARY = [
    // ═══ FRONT ═══
    { id: 'front_hero', name: 'Đứng hero chính diện', emoji: '🦸‍♀️', thumbnail: '/assets/poses/front_hero.png', category: 'front', description: 'Đứng thẳng, tự tin, hông nhẹ S-curve', bodyFocus: 'Toàn thân, tỷ lệ cơ thể', cameraAngle: 'Full-body front-facing, eye level', promptEN: 'Full-body front-facing, confident natural stance with slight S-curve hip shift, one hand lightly touching thigh, other hand relaxed at side. Sweet genuine smile, eyes looking directly at camera. Legs slightly apart, weight shifted to one leg creating elegant body line. Camera at eye level, full-body shot from feet to head showing complete garment and model proportions.' },
    { id: 'front_bust_closeup', name: 'Cận ngực & mặt', emoji: '💋', thumbnail: '/assets/poses/bust_closeup.png', category: 'front', description: 'Cận thân trên, focus ngực + khuôn mặt', bodyFocus: 'Ngực, khuôn mặt', cameraAngle: 'Close-up chest to face, straight-on', promptEN: 'Upper body close-up from chest to face, straight-on facing camera, arms relaxed at sides (barely visible). Confident calm expression, slight natural smile, eyes open looking at lens. Tight-fit garment showing bust volume with natural fabric stretch and light reflections. Focus on face beauty and bust presentation. Shallow depth of field, studio lighting with soft highlights on fabric.' },
    { id: 'front_arms_wide', name: 'Tay dang rộng', emoji: '🤗', thumbnail: '/assets/poses/arms_wide.png', category: 'front', description: 'Chính diện, 2 tay dang rộng, thân hình chữ V', bodyFocus: 'Ngực, eo, tỷ lệ vai-eo', cameraAngle: 'Front, upper body, slightly above', promptEN: 'Front-facing, both arms spread wide open past the frame edges, palms open. Slight warm smile, looking directly at camera. Arms extended create V-shape from shoulders to waist emphasizing bust and narrow waist. Upper body shot, camera slightly above eye level. Dynamic, welcoming, confident energy.' },
    { id: 'front_hands_block', name: 'Tay vươn che lens', emoji: '🖐️', thumbnail: '/assets/poses/hands_block.png', category: 'selfie', description: '2 bàn tay xòe ra phía camera', bodyFocus: 'Ngực từ trên, bàn tay foreground', cameraAngle: 'Front, slightly below, wide angle', promptEN: 'Front-facing, both hands reaching forward toward camera with fingers spread open wide, creating forced perspective effect where hands appear large in foreground and body appears smaller behind. Cool confident expression, slight head tilt. Upper body to thigh visible between arms. Camera slightly below eye level, wide-angle lens feel creating intimate engaging perspective.' },

    // ═══ BACK ═══
    { id: 'back_pinch', name: 'Quay lưng kéo áo', emoji: '👐', thumbnail: '/assets/poses/back_pinch.png', category: 'back', description: 'Quay lưng, 2 tay kéo nhẹ lai áo ở eo', bodyFocus: 'Eo thon, mông tròn', cameraAngle: 'Back view, waist level', promptEN: 'Back view, model facing away from camera. Both hands at waist level pinching and slightly pulling the hem of the shirt upward, revealing a sliver of skin at waist. Feet shoulder-width apart, weight evenly distributed on both legs. Hair falling down the back. Camera at waist level, upper body to thigh shot emphasizing waist-to-hip ratio and rounded butt silhouette.' },
    { id: 'back_arms_up_wall', name: 'Giơ tay bám tường', emoji: '🙌', thumbnail: '/assets/poses/back_arms_up.png', category: 'back', description: 'Quay lưng, 2 tay giơ cao, chân kiễng', bodyFocus: 'Lưng dài, mông nâng, chân thon', cameraAngle: 'Back view, full body', promptEN: 'Back view, model facing wall with both arms raised high above head, palms flat against wall/air with fingers spread. Standing on tiptoes slightly, legs together and straight creating elongated body line. Hair cascading down one side. Full-body shot showing complete back silhouette — long back, lifted butt, elongated legs. Dynamic and playful energy.' },
    { id: 'back_closeup_butt', name: 'Cận mông kéo áo', emoji: '🍑', thumbnail: '/assets/poses/back_closeup.png', category: 'back', description: 'Cận eo xuống mông, 2 tay kéo lai áo', bodyFocus: 'Mông tròn cận cảnh', cameraAngle: 'Back view, close-up waist to thigh', promptEN: 'Back view close-up from waist down to mid-thigh. Both hands at waist pinching the shirt hem. Focus zoomed on the waist-hip-butt area, showing the fabric stretch across rounded butt with natural light reflection on tight shorts/pants. Detailed texture visible on clothing. Camera at hip level for flattering butt perspective.' },
    { id: 'back_fullbody_tiptoe', name: 'Sau lưng toàn thân', emoji: '👠', thumbnail: '/assets/poses/back_fullbody.png', category: 'back', description: 'Full body quay lưng, kiễng chân', bodyFocus: 'Toàn bộ silhouette từ sau', cameraAngle: 'Back view, full body head to toe', promptEN: 'Full-body back view from head to feet. Model facing completely away from camera. Both hands at waist pulling shirt hem slightly. Standing on tiptoes in white sneakers, feet slightly pigeon-toed. Long dark hair flowing down the back. Complete rear silhouette showing: hair + narrow waist + rounded butt + slim long legs + shoes. Clean studio background.' },

    // ═══ SIDE ═══
    { id: 'side_scurve', name: 'S-curve nghiêng', emoji: '💃', thumbnail: '/assets/poses/side_scurve.png', category: 'side', description: '3/4 nghiêng, 1 tay vuốt tóc, chân bắt chéo', bodyFocus: 'Chân dài, ngực side, mông profile', cameraAngle: '3/4 angle, full body', promptEN: '3/4 angle full-body shot, model turned partially away from camera but looking back over shoulder. One arm raised touching/running through hair at the top of head. Legs in a model stance — one foot forward, legs creating elongated crossed line. Shows side profile of bust, narrow waist, and butt silhouette simultaneously. Sultry confident expression looking at camera. Classic fashion model S-curve pose.' },
    { id: 'side_profile_glance', name: 'Ngoảnh nhìn qua vai', emoji: '😏', thumbnail: '/assets/poses/side_profile.png', category: 'side', description: '3/4 lưng, ngoảnh mặt nhìn camera qua vai', bodyFocus: 'Mông + ngực side + gương mặt', cameraAngle: '3/4 rear, upper body', promptEN: '3/4 rear angle, upper body shot. Model turned with back partially toward camera, looking back over right shoulder at lens. One hand raised touching hair at the crown. Shows side profile: bust visible from side creating volume, rounded butt profile in shorts/pants, and beautiful face looking back with alluring confident expression. Hair flowing down one side.' },

    // ═══ SELFIE ═══
    { id: 'selfie_reach', name: 'Vươn tay ôm', emoji: '🫶', thumbnail: '/assets/poses/selfie_reach.png', category: 'selfie', description: '2 tay vươn ra phía camera như ôm người xem', bodyFocus: 'Ngực từ trên, gương mặt gần', cameraAngle: 'Front, slightly above, intimate', promptEN: 'Front-facing, both arms extended forward toward camera as if reaching to grab or hug the viewer. Slight lean forward, warm inviting expression with gentle smile. Creates intimate engaging perspective where viewer feels embraced. Upper body shot, camera slightly above creating flattering angle showing bust from above. Warm, personal, social-media-ready feel.' },
    { id: 'selfie_one_arm', name: 'Selfie 1 tay', emoji: '🤳', thumbnail: '/assets/poses/selfie_one.png', category: 'selfie', description: '1 tay giơ cao cầm camera, thân hơi nghiêng', bodyFocus: 'Ngực side profile, eo', cameraAngle: 'Selfie angle, above looking down', promptEN: 'Selfie perspective — one arm raised high holding camera (pointed at viewer), other hand relaxed at side or touching hip. Body slightly angled to camera creating natural curves. Confident calm expression, slight head tilt, eyes looking up at lens. Upper body shot from selfie angle above, showing bust volume from slightly above and to the side. Natural, authentic selfie energy.' },

    // ═══ SITTING ═══
    { id: 'sit_elegant', name: 'Ngồi ghế thanh lịch', emoji: '💺', thumbnail: '/assets/poses/sit_elegant.png', category: 'sitting', description: 'Ngồi ghế cao, chân bắt chéo, tay đặt đùi', bodyFocus: 'Chân dài bắt chéo, eo, ngực', cameraAngle: 'Eye level, 3/4 angle', promptEN: 'Sitting elegantly on a high stool or chair, legs crossed at the knee showing long slender legs. One hand resting on thigh, other hand touching chair or resting on lap. Back straight, slight forward lean, charming smile. 3/4 angle showing body curves while seated. Full-body shot from feet up including the chair/stool. Graceful, sophisticated editorial feel.' },
    { id: 'sit_playful', name: 'Ngồi tinh nghịch', emoji: '😜', thumbnail: '/assets/poses/sit_playful.png', category: 'sitting', description: 'Ngồi vắt chéo chân, tay chống cằm, đầu nghiêng', bodyFocus: 'Chân + gương mặt dễ thương', cameraAngle: 'Eye level, front or 3/4', promptEN: 'Sitting casually on a stool/step/seat, one leg dangling, other leg bent up. One hand propping up chin, head tilted to one side with dreamy playful expression looking away from camera. Relaxed youthful energy. Front or 3/4 angle showing full body in relaxed seated position. Hair falling naturally, candid lifestyle feel.' },

    // ═══ ACTION ═══
    { id: 'action_walk', name: 'Bước đi catwalk', emoji: '🚶‍♀️', thumbnail: '/assets/poses/action_walk.png', category: 'action', description: 'Đang bước đi tự tin, tóc bay, vải bay', bodyFocus: 'Chân dài, toàn thân dynamic', cameraAngle: '3/4 angle, mid-stride', promptEN: '3/4 angle mid-stride catwalk walk toward camera. Hair flowing with movement, fabric swaying naturally. One foot forward, one foot behind in natural walking motion. Confident playful expression, slight head tilt. Full-body shot capturing the energy and motion of walking. Dynamic, editorial fashion walk energy.' },
    { id: 'action_jump', name: 'Nhảy tung tăng', emoji: '🤸', thumbnail: '/assets/poses/action_jump.png', category: 'action', description: 'Nhảy lên, tóc bay, biểu cảm vui vẻ tự do', bodyFocus: 'Toàn thân, năng lượng', cameraAngle: 'Full body, slightly below looking up', promptEN: 'Mid-air jump with both feet off the ground, hair flying upward, clothing floating with the motion. Arms playfully positioned — one up, one out. Genuine joyful laugh, eyes bright. Camera slightly below looking up to emphasize the jump height and create powerful dynamic composition. Full-body shot with space above for the jump.' },
    { id: 'action_twirl', name: 'Xoay váy/đầm', emoji: '🌀', thumbnail: '/assets/poses/action_twirl.png', category: 'action', description: 'Xoay người, váy/vải bay tạo vòng tròn', bodyFocus: 'Váy bay, toàn thân xoay', cameraAngle: 'Full body, eye level', promptEN: 'Mid-twirl spin with skirt/dress fabric fanning out in a beautiful circular motion. One arm extended outward for balance, hair whipping with the turn. Joyful carefree expression, eyes slightly closed in the moment. Full-body shot at eye level capturing the fabric movement frozen mid-spin. Dreamy romantic editorial quality.' },

    // ═══ EDITORIAL ═══
    { id: 'editorial_leaning', name: 'Tựa tường cool', emoji: '😎', thumbnail: '/assets/poses/editorial_lean.png', category: 'editorial', description: 'Tựa lưng vào tường, 1 chân co, tay cho túi', bodyFocus: 'Chân dài, thái độ cool', cameraAngle: 'Full body, slight angle', promptEN: 'Leaning back against a clean wall, one foot flat on the ground, other foot bent with sole pressed against the wall behind. Arms crossed or one hand in pocket/at hip. Cool effortless expression, chin slightly raised, looking at camera with attitude. Full-body shot at a slight angle. Streetwear editorial cool-girl energy.' },
    { id: 'editorial_golden_hour', name: 'Golden hour finale', emoji: '🌅', thumbnail: '/assets/poses/golden_hour.png', category: 'editorial', description: 'Ánh sáng golden hour, tóc bay, biểu cảm dreamy', bodyFocus: 'Silhouette, rim lighting', cameraAngle: 'Wide angle, artistic composition', promptEN: 'Artistic wide-angle composition, gentle wind blowing hair and fabric. Golden-hour warm rim lighting creating a halo/backlight effect around the model. Graceful flowing pose with arms slightly extended or one hand touching hair. Dreamy far-away expression. Wide shot showing model against golden sky/sunset. Magazine-cover cinematic finale quality.' },

    // ═══ XE ĐẠP (CYCLING) ═══
    { id: 'cycling_ride', name: 'Đạp xe trên đường', emoji: '🚲', thumbnail: '/assets/poses/cycling_ride.png', category: 'cycling', description: 'Đang đạp xe, tóc bay, tự do', bodyFocus: 'Toàn thân + xe đạp', cameraAngle: 'Side view, full body with bicycle', promptEN: 'Side view full-body shot. Model riding a bicycle on road, hands on handlebars, one leg down one up on pedal. Hair flowing back in the wind, slight joyful smile. Wearing fashionable athletic or casual outfit. Bicycle visible in full. Dynamic motion feel, golden hour or natural sunlight. Freedom and adventure energy.' },
    { id: 'cycling_lean', name: 'Tựa xe đạp chụp hình', emoji: '🚴', thumbnail: '/assets/poses/cycling_lean.png', category: 'cycling', description: 'Đứng cạnh xe, tay tựa yên, tự tin', bodyFocus: 'Toàn thân, xe đạp làm prop', cameraAngle: '3/4 angle, full body with bicycle', promptEN: '3/4 angle full-body shot. Model standing beside bicycle, one hand leaning casually on the seat, other hand on hip. Weight on one leg in relaxed confident posture. Bicycle as fashion prop. Casual street-style or sporty outfit. Bright natural lighting, urban or countryside backdrop.' },
    { id: 'cycling_selfie', name: 'Selfie trên xe đạp', emoji: '🤳', thumbnail: '/assets/poses/cycling_selfie.png', category: 'cycling', description: 'Ngồi trên yên, 1 tay cầm phone selfie', bodyFocus: 'Thân trên, mặt vui vẻ', cameraAngle: 'Front selfie angle, upper body', promptEN: 'Front-facing selfie angle, upper body shot. Model sitting on bicycle seat with both feet on the ground, one hand holding phone up high for selfie, playful smile. Helmet optional. Background shows road or park. Youthful, social-media-friendly energy. Natural sunlight.' },

    // ═══ LÁI Ô TÔ (DRIVING) ═══
    { id: 'driving_wheel', name: 'Ngồi sau vô lăng', emoji: '🚗', thumbnail: '/assets/poses/driving_wheel.png', category: 'driving', description: 'Ngồi ghế lái, 2 tay trên vô lăng, nhìn camera', bodyFocus: 'Thân trên, tay + mặt', cameraAngle: 'Through open window, upper body', promptEN: 'Upper body shot through open car window. Model sitting in driver seat, both hands on steering wheel, looking at camera with confident smile. Interior of luxury/modern car visible. Professional outfit or smart casual. Cool confident driver energy. Natural or studio lighting from window.' },
    { id: 'driving_lean', name: 'Tựa xe sang chảnh', emoji: '🏎️', thumbnail: '/assets/poses/driving_lean.png', category: 'driving', description: 'Tựa cửa xe, tay trên nóc, chân bắt chéo', bodyFocus: 'Toàn thân + xe hơi', cameraAngle: '3/4 angle, full body with car', promptEN: '3/4 angle full-body shot. Model leaning against luxury car door, one arm resting elegantly on car roof, legs crossed at ankle. Cool effortless expression, sunglasses optional. Fashionable outfit complementing the car color. Urban or scenic backdrop. High-fashion automotive editorial energy.' },
    { id: 'driving_exit', name: 'Bước xuống xe', emoji: '👠', thumbnail: '/assets/poses/driving_exit.png', category: 'driving', description: 'Đang bước ra khỏi xe, thanh lịch', bodyFocus: 'Chân dài, toàn thân elegant', cameraAngle: 'Side view, full body exiting car', promptEN: 'Side view full-body shot. Model stepping out of car, one leg elegantly out the door, hand on door frame, looking back over shoulder. Evening gown or stylish outfit flowing. Paparazzi-style capture moment. Glamorous, cinematic red-carpet energy. Night or golden hour lighting.' },

    // ═══ CHẠY BỘ (RUNNING) ═══
    { id: 'running_sprint', name: 'Chạy nước rút', emoji: '🏃', thumbnail: '/assets/poses/running_sprint.png', category: 'running', description: 'Đang chạy nhanh, tóc bay, dynamic', bodyFocus: 'Toàn thân, cơ bắp chuyển động', cameraAngle: 'Side view, full body mid-sprint', promptEN: 'Side view full-body shot. Model mid-sprint running, one leg forward one back, arms pumping, ponytail flying in the wind. Athletic sportswear — sports bra, leggings, running shoes. Dynamic frozen motion capture. Track, park, or city street backdrop. Powerful athletic energy, sharp focus on model with motion-blurred background.' },
    { id: 'running_stretch', name: 'Khởi động trước chạy', emoji: '🧘', thumbnail: '/assets/poses/running_stretch.png', category: 'running', description: 'Lunge stretch, tay trên gối, chuẩn bị', bodyFocus: 'Chân, mông, thân trên', cameraAngle: '3/4 view, full body lunge', promptEN: '3/4 view full-body shot. Model doing pre-run lunge stretch, one leg forward bent at knee, other leg extended back. Hands on front knee, athletic posture. Sportswear showing toned legs and athletic build. Park or track background, morning golden light. Focused determined expression. Health and fitness energy.' },
    { id: 'running_jog', name: 'Jogging thư giãn', emoji: '🎧', thumbnail: '/assets/poses/running_finish.png', category: 'running', description: 'Chạy bộ nhẹ nhàng, đeo tai nghe, thư giãn', bodyFocus: 'Toàn thân, tự nhiên', cameraAngle: 'Front-facing, full body jogging', promptEN: 'Front-facing full-body shot. Model jogging casually at relaxed pace, one arm swinging naturally, slight happy smile, earbuds/headphones in. Trendy running outfit — matching set, running shoes. Park path or boardwalk setting, morning light. Relaxed lifestyle fitness energy, natural and approachable.' },

    // ═══ PICKLEBALL ═══
    { id: 'pickle_serve', name: 'Giao bóng Pickleball', emoji: '🏓', thumbnail: '/assets/poses/pickle_serve.png', category: 'pickleball', description: 'Chuẩn bị giao bóng, paddle giơ cao', bodyFocus: 'Toàn thân, tay giơ paddle', cameraAngle: 'Front view, full body serve stance', promptEN: 'Front view full-body shot. Model in athletic serve stance preparing to serve in pickleball, paddle raised above shoulder, ball tossed up. Legs apart in athletic ready position. Sporty outfit — skort, polo or tank top, sneakers. Outdoor pickleball court, bright daylight. Competitive focused expression. Dynamic sports fashion energy.' },
    { id: 'pickle_swing', name: 'Đánh forehand', emoji: '💥', thumbnail: '/assets/poses/pickle_swing.png', category: 'pickleball', description: 'Đang swing forehand mạnh, dynamic', bodyFocus: 'Toàn thân, cánh tay + paddle', cameraAngle: 'Side view, full body mid-swing', promptEN: 'Side view full-body shot. Model mid-swing hitting pickleball forehand shot, paddle extended forward, lunging with legs in power stance. Dynamic action frozen moment. Athletic outfit showing toned arms and legs. Court surface and net visible in background. Intense athletic focus, competitive energy. Sharp action photography feel.' },
    { id: 'pickle_victory', name: 'Ăn mừng chiến thắng', emoji: '🏆', thumbnail: '/assets/poses/pickle_victory.png', category: 'pickleball', description: 'Giơ paddle ăn mừng, cười rạng rỡ', bodyFocus: 'Toàn thân, biểu cảm vui', cameraAngle: '3/4 view, full body celebration', promptEN: '3/4 view full-body shot. Model holding pickleball paddle victoriously with one arm raised celebrating, wide happy smile, other hand on hip. Sporty outfit slightly sweaty from play. Outdoor court background. Triumphant joyful energy, post-game celebration moment. Genuine happiness and athletic confidence.' },

    // ═══ BIKINI ═══
    { id: 'bikini_stand', name: 'Đứng bikini bãi biển', emoji: '👙', thumbnail: '/assets/poses/bikini_stand.png', category: 'bikini', description: 'Đứng S-curve, 1 tay hông, tự tin', bodyFocus: 'Toàn thân, đường cong body', cameraAngle: 'Full-body front-facing, beach', promptEN: 'Full-body front-facing shot on beach. Model in bikini standing with slight S-curve, one hand on hip, hair flowing in ocean breeze. Confident sensual expression. Sandy beach with gentle waves in background. Golden hour warm lighting creating rim light on skin. Natural and alluring beach glamour. Shows complete bikini and body proportions beautifully.' },
    { id: 'bikini_back', name: 'Bikini quay lưng biển', emoji: '🌊', thumbnail: '/assets/poses/bikini_back.png', category: 'bikini', description: 'Quay lưng bước ra biển, nhìn lại qua vai', bodyFocus: 'Mông, lưng, silhouette', cameraAngle: 'Full body, back view walking toward ocean', promptEN: 'Full-body back view shot. Model in bikini walking away toward the ocean, looking back over shoulder with playful alluring smile. Hair blowing in wind. Sandy beach and turquoise water. Golden sunset backlight creating beautiful silhouette. Shows bikini back design, sculpted butt and back. Dreamy wanderlust beach energy.' },
    { id: 'bikini_sit', name: 'Bikini ngồi tắm nắng', emoji: '☀️', thumbnail: '/assets/poses/bikini_sit.png', category: 'bikini', description: 'Ngồi bờ biển, chân duỗi, ngửa mặt hứng nắng', bodyFocus: 'Chân dài, thân trên, mặt', cameraAngle: 'Side view, full body sitting', promptEN: 'Side view full-body shot. Model in bikini sitting on beach or poolside, legs extended forward, leaning back on both hands behind. Face tilted up toward the sun with eyes closed, serene blissful expression. Shows long legs, toned torso, and bikini from side angle. Warm golden sunlight, water glistening in background. Relaxed vacation glamour.' },

    // ═══ GYM ═══
    { id: 'gym_squat', name: 'Squat với tạ', emoji: '🏋️', thumbnail: '/assets/poses/gym_squat.png', category: 'gym', description: 'Deep squat, thanh tạ trên vai, form chuẩn', bodyFocus: 'Chân, mông, thân trên', cameraAngle: 'Front view, full body squat', promptEN: 'Front view full-body shot. Model doing deep weighted squat in gym, barbell across shoulders behind neck, deep squat position with thighs parallel to floor. Athletic powerful form with straight back and engaged core. Tight gym outfit — sports bra, high-waist leggings showing sculpted legs and butt. Gym rack or clean gym background. Powerful fitness goddess energy.' },
    { id: 'gym_flex', name: 'Flex bicep trong gương', emoji: '💪', thumbnail: '/assets/poses/gym_flex.png', category: 'gym', description: 'Flex cơ tay, nhìn gương, tự tin', bodyFocus: 'Cánh tay, eo, thân trên', cameraAngle: '3/4 angle, upper body mirror', promptEN: '3/4 angle upper body shot in gym mirror. Model flexing one bicep, other hand on waist, showing toned arms and narrow waist. Slight confident smirk looking at mirror reflection. Crop top or sports bra showing defined abs and arms. Gym mirror and equipment in background. Self-assured gym selfie energy, fitness influencer style.' },
    { id: 'gym_deadlift', name: 'Deadlift hoàn thành', emoji: '🔥', thumbnail: '/assets/poses/gym_deadlift.png', category: 'gym', description: 'Đứng sau deadlift, thanh tạ ngang đùi, mạnh mẽ', bodyFocus: 'Chân, mông, lưng, tay', cameraAngle: 'Side view, full body standing', promptEN: 'Side view full-body shot. Model standing tall after completing deadlift, barbell at thigh height, straight back, strong legs locked out. Confident accomplished expression. Tight gym outfit showing athletic build — powerful thighs, lifted butt, toned back. Gym platform, chalk dust visible. Raw athletic power energy.' },

    // ═══ ĐỒ BƠI (SWIMWEAR) ═══
    { id: 'swim_dive', name: 'Chuẩn bị nhảy xuống hồ', emoji: '🏊', thumbnail: '/assets/poses/swim_dive.png', category: 'swimwear', description: 'Đứng bờ hồ, tay giơ cao chuẩn bị nhảy', bodyFocus: 'Toàn thân elongated', cameraAngle: 'Side view, full body pre-dive', promptEN: 'Side view full-body shot. Model in one-piece swimsuit standing at pool edge, arms raised overhead in elegant pre-dive positioning, body fully elongated showing graceful lines. Toes at pool edge. Clean modern pool, blue water reflection. Athletic yet graceful energy, swimwear catalog editorial quality.' },
    { id: 'swim_pool', name: 'Ngồi bờ hồ bơi', emoji: '🌴', thumbnail: '/assets/poses/swim_pool.png', category: 'swimwear', description: 'Ngồi bờ hồ, chân thả nước, thư giãn', bodyFocus: 'Chân, thân trên, mặt relax', cameraAngle: '3/4 view, full body at poolside', promptEN: '3/4 view full-body shot. Model in swimsuit sitting on pool edge, legs dangling in sparkling blue water, leaning back on both arms behind. Face tilted up with relaxed happy expression, sunglasses on head. Resort pool, palm trees, loungers in background. Luxury resort vacation vibe. Relaxed poolside glamour.' },
    { id: 'swim_walk', name: 'Sải bước bãi biển', emoji: '🏖️', thumbnail: '/assets/poses/swim_walk.png', category: 'swimwear', description: 'Đi dọc bờ biển, sarong bay, thanh thoát', bodyFocus: 'Chân dài, silhouette dynamic', cameraAngle: 'Side view, full body beach walk', promptEN: 'Side view full-body shot. Model in one-piece swimsuit walking along beach waterline, sheer sarong wrap flowing in the wind behind her. One hand touching hair, barefoot in shallow water. Sunset golden light, waves lapping at feet. Dynamic catwalk-on-beach energy. Magazine editorial swimwear campaign quality.' },

    // ═══ LUXURY ═══
    { id: 'luxury_sofa', name: 'Nằm sofa sang trọng', emoji: '🛋️', thumbnail: '/assets/poses/luxury_sofa.png', category: 'luxury', description: 'Nằm nghiêng trên sofa, chân bắt chéo, thanh lịch', bodyFocus: 'Toàn thân, đường cong elegant', cameraAngle: '3/4 view, full body on sofa', promptEN: '3/4 view full-body shot. Model in luxury evening dress reclining elegantly on velvet chaise lounge, one arm draped gracefully over the back, legs crossed showing high-slit. Champagne glass in hand (optional). Glamorous old-Hollywood starlet expression. Rich interior — marble, gold accents, dim mood lighting. Opulent luxury fashion energy.' },
    { id: 'luxury_stairs', name: 'Bước xuống cầu thang', emoji: '👑', thumbnail: '/assets/poses/luxury_stairs.png', category: 'luxury', description: 'Bước xuống cầu thang lớn, cầm váy, quý phái', bodyFocus: 'Toàn thân, tư thế đi xuống', cameraAngle: 'Front view, full body on staircase', promptEN: 'Front view full-body shot. Model in floor-length evening gown walking down grand staircase, one hand on ornate banister, other hand gracefully lifting gown hem slightly. Elegant upright posture, chin raised, composed regal expression. Grand marble staircase with chandelier above. Red-carpet-ready luxury gala energy. Cinematic glamour.' },
    { id: 'luxury_power', name: 'Power pose luxury', emoji: '💎', thumbnail: '/assets/poses/luxury_pose.png', category: 'luxury', description: 'Đứng quyền lực, túi xách tay, cằm cao', bodyFocus: 'Toàn thân, thái độ boss', cameraAngle: '3/4 angle, full body power stance', promptEN: '3/4 angle full-body shot. Model in luxury designer outfit standing with designer handbag, hand on hip, chin slightly raised, powerful commanding stance. Sunglasses, statement jewelry. Clean luxury backdrop — hotel lobby, art gallery, or minimalist space. Boss-woman energy. High-fashion editorial for luxury brand campaign.' },
]

export function getPosesByCategory(categoryId) {
    if (categoryId === 'all') return POSE_LIBRARY
    return POSE_LIBRARY.filter(p => p.category === categoryId)
}

export function getPoseById(poseId) {
    return POSE_LIBRARY.find(p => p.id === poseId) || null
}

export const PROMPT_TEMPLATES = [
    { id: 'lookbook', name: '📷 Lookbook sản phẩm', description: 'Ảnh catalogue chuyên nghiệp cho shop online', promptPrefix: 'Professional fashion lookbook product shot. Clean minimal background.' },
    { id: 'lifestyle', name: '🌿 Lifestyle tự nhiên', description: 'Ảnh đời thường, tự nhiên như influencer chụp', promptPrefix: 'Natural lifestyle photography, candid authentic feel, real-world setting.' },
    { id: 'editorial', name: '🎬 Editorial cao cấp', description: 'Ảnh tạp chí thời trang high-end', promptPrefix: 'High-end editorial fashion photography, dramatic lighting, magazine-quality composition.' },
    { id: 'social', name: '📱 Social media / TikTok', description: 'Ảnh tối ưu cho mạng xã hội, bắt mắt, viral', promptPrefix: 'Social media optimized photo, eye-catching, vibrant, vertical 9:16 format.' },
    { id: 'streetwear', name: '🏙️ Streetwear / Urban', description: 'Phong cách đường phố, cool, trendy', promptPrefix: 'Urban streetwear photography, cool edgy vibe, city backdrop or grunge setting.' },
]
